### ISSUE TITLE
raddbg can't kill console program debuggee that has a `WinMain` function

### ISSUE THREAD

**Issue by tom-seddon** [EpicGames/raddebugger#135]
Reproduced with the 0.9.7-alpha release and 0be4680ec927c264f154a3dfa75ed6ae1c241362

Reproduction steps:

0. `git clone https://github.com/tom-seddon/raddbg_console_program` somewhere
1. Load .sln into VS2019 and build debug build - it's a x64 console app with both `WinMain` and `main` functions
2. Set up target in raddbg to run debug build
3. Start debugging in raddbg - should get a console window with a message telling you to press Return. It's sitting in `getchar()` waiting for the keypress
4. Press the stop button in raddbg

Expected results: debuggee stops
Actual results: debuggee continues running. (But you can press return to quit and raddbg figures it out)

Also try: uncomment the `#pragma comment` in main.cpp, to turn it into a GUI program. (This time it'll run and wait for you to click OK on the message box.) raddbg has no problem killing it this time.

Also try: find the `default_entry_points` table in the `DEMON_EventKind_HandshakeComplete` case in ctrl_core.c. Move the `main` entry to the start of list. Retry both cases. Now the console program is killable, and the GUI version isn't.

I stepped through the `DEMON_EventKind_HandshakeComplete` code a few times and it looks like raddbg never finds a name by voff for the entry point - is this expected? - and so always ends up using its table of possible entry point names to find a probable one. And it finds `WinMain`, that being first on its list, but because this is a console program, `WinMain` is never executed. And presumably that interferes with its operation somehow?

`dumpbin /headers` prints the expected entry point in the console mode case: `11262 entry point (0000000140011262) @ILT+605(mainCRTStartup)`, from my last build. So it feels like in principle raddbg should be able to get the right entry point without having to guess.

Thanks,

--Tom

P.S. I ran into this when trying to debug an actual program I wrote - it deliberately has both entry points, and doesn't use the `_CONSOLE` define, so that the actual exe type can be tweaked using `#pragma comment(linker, "/SUBSYSTEM:WINDOWS")`

**Comment by ryanfleury** [comment]
This was being caused by the fact that RADDBG was previously written to pick a *single* entry point candidate, given all of the available symbols in a binary. I've changed this so that RADDBG will now find all *possible* entry point candidates, and trap them *all*, stopping at the first one that is actually hit. After this change (762013899f822039b323ca7a44fecd5d7f0818b7), I can successfully step through both the `/SUBSYSTEM:WINDOWS` and `/SUBSYSTEM:CONSOLE` versions of the program, with both `main` and `WinMain` symbols being present in both.

(Interestingly enough, Visual Studio doesn't seem to step into the `/SUBSYSTEM:WINDOWS` version correctly?)

Let me know if you run into any more issues with this.
