### ISSUE TITLE
Plugin support

### ISSUE THREAD

**Issue by emoon** [EpicGames/raddebugger#14]
Hi,

First of all thanks for opening up this project to the public.

I wonder if you plan to support plugins in the future? That is for both backend (such as different CPUs/systems not supported out of the box) and also visualizers (that can show memory in different ways, etc)

**Comment by ryanfleury** [comment]
Hi! Thanks for the question.

I do plan on supporting plugins, at the very least, for the visualization engine (exposed as "View Rules" in the UI) in the debugger. That is how the system is already architected, but since the visualization engine is still very young and not yet complete, I've not exposed any of this to users for now, to ensure that when a plugin system & APIs are available to users, they're rock solid. But point being, it's in the game plan.

At the lower level, the exact details of where we'd have plugin systems are less clear to me right now, but it's likely there will be some kind of an API/protocol for the process control part of the debugger (`src/ctrl`) to support remote debugging in the future (right now it just relies on our "demon" layer, in `src/demon`, for doing local process control, but this will eventually be one-of-many backends). I could also imagine a plugin system for exposing architecture information at some point, but if we decide that is worthwhile, that will be much further down the line than e.g. the visualization engine plugins. We are, however, abstracting over architecture internally in codepaths for which it's appropriate, because we do plan on supporting many architectures.

**Comment by emoon** [comment]
Thanks for the replay.

All of that makes sense. In my case I would like to do a backend(s) for some old hardware such as the Amiga which I still enjoy coding for. Now, I wouldn't want to stick all of that code into the main repo as I'm sure that is not something you want to support (and shouldn't) which is why having an extensibility/plugin option would be great.

As you say that you already need to abstract over architectures internally this usually gives a good direction how a potential interface would look.
