### ISSUE TITLE
I can't step on source files from "hot reloaded" dlls

### ISSUE THREAD

**Issue by DevAgu93** [EpicGames/raddebugger#21]
When I compile and reload a dll, stepping through the source files doesn't work anymore, only on disassembly.

**Comment by DmitriySalnikov** [comment]
Can you test the temporary solution from #32?

**Comment by DevAgu93** [comment]
Still doesn't work.

**Comment by ryanfleury** [comment]
Thanks for this report. I've been straightening out a few other major issues but will look into this one shortly.

**Comment by ryanfleury** [comment]
@DevAgu93 Can you give this a try after pulling & building the most recent changes in the `master` branch? Let me know if you still run into issues.

**Comment by DevAgu93** [comment]
It works! though every time I compile, the game pauses for a bit before the debugger loads the dll.

**Comment by DevAgu93** [comment]
>the game pauses for a bit before the debugger loads the dll.
Just to explain myself better: the program freezes.

**Comment by ryanfleury** [comment]
Great! Yeah, that delay is due to the debugger re-converting the PDB to RADDBG debug info for the module you're rebuilding. That is currently pretty slow because it's an unoptimized reference converter that was built with correctness & completeness as a priority. That will improve with time, since that is one of the main tasks in order to get the debugger up to speed for e.g. UE-sized projects.

In any case - closing this now, since the hot reloaded DLL issue has been fixed.
