### ISSUE TITLE
How to change address in the memory viewer

### ISSUE THREAD

**Issue by emoon** [EpicGames/raddebugger#43]
I'm feeling quite stupid for asking this, but how do you change the address in the memory viewer? I can't figure it out.

**Comment by ryanfleury** [comment]
You'll want to run the "Go To Address" command. The default keybinding for this is Alt+G. You can write either an actual address, or any expression that the debugger could normally evaluate in e.g. the watch window.

Basically all actions in the debugger like this can be found in the command lister/palette - you can open it up by hitting F1 (by default - you can change this hotkey too).

**Comment by emoon** [comment]
Thanks.

I think it would make sense to have a dropdown here where you can fill in the memory (such as in vs) it's also useful to have a dropdown if you want to switch between locations (and doesn't want a full new view for it)

![vs_memory_view](https://github.com/EpicGames/raddebugger/assets/350822/3eb6f4cc-b2e7-4935-b71b-fc8120da2138)

**Comment by dbechrd** [comment]
This also really confused me. This should be added to the readme since it's such a common task. I expected to be able to right-click a variable (either in the code, or in the watch window) and do "go to memory address" or similar. When that didn't work, I expected to be able to double-click the current address in the memory window and paste a new value.

**Comment by amanKharb10** [comment]
For anyone who comes here stumped by memory window like I was, if you don't have the memory window selected then Alt + G won't work. So, keep that in mind. I hope it changes in future and we can do Alt + G from anywhere.
