### ISSUE TITLE
Keyboard bindings to expand trees

### ISSUE THREAD

**Issue by MohitSethi99** [EpicGames/raddebugger#97]
Is there a way to expand trees using keyboard, I'd appreciate something like right/left arrow keys (maybe with ctrl modifier) to expand/retract trees that are in the Watch window.

Another side note: Would love to have a force expand that can expand the whole tree (while holding alt or something).

**Comment by ryanfleury** [comment]
You can expand rows in the watch window by hitting Enter on rows that are expandable. Left and right won’t work, because the watch window has cell navigation using the arrow keys. (It isn’t just row navigation, unlike e.g. VS)

I’ll have to ponder the “expand all” thing; the problem is that this can cause arbitrarily recursive expansion. I can do cycle detection, but the other problem is that if you e.g. put a huge (100,000 element) array in the watch window (which is completely supported, unlike in VS) and hit “expand all”, the debugger would become unusably slow (if not hang/crash)—the watch window’s windowing algorithm is not equipped for that kind of case. But maybe there is room for a simple middle ground or something, or maybe I can tweak the windowing algorithm to work here somehow.

**Comment by MohitSethi99** [comment]
Got it, I don't have a use case for the "expand all" part though, just thought it would be a cool feature to have but I do get your point.
You can close this issue if you want as my main concern is resolved.
